pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('Install') {
                    steps {
                        npm install
                    }
                }
                stage('Test') {
                    steps {
                        npm run test
                    }
                }
                stage('Build') {
                    steps {
                        npm run build
                    }
                }
            }
        }
    }
}
