pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'sudo node:20.11.1-alpine3.19' }
            }
            stages {
                stage('checkout') {
                    steps {
                        checkout scm
                    }
                }
                stage('Install') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('Test') {
                    steps {
                        sh 'npm run test'
                    }
                }
                stage('Build') {
                    steps {
                        sh 'npm run build'
                    }
                }
            }
        }
    }
}
